version: 3
approve_by_comment: true
approve_regex: '^(Approved|:\+1:|:lgtm:|lgtm|LGTM)'
reject_regex:  '^(Rejected|:\-1:)'
reset_on_push: false
groups:
  ide-committers:
    required: 1
    teams:
      - ide
    conditions:
      labels:
        - needs:review-ide
  core-committers:  
    required: 1
    teams:
      - core
    conditions:
      branches:
        - master
  lingua-committers:
    required: 1
    teams:
      - lingua
    conditions:
      labels:
        - needs:review-lingua
  core-interns:
    required: 1
    teams:
      - core-interns
    conditions:
      labels:
        - needs:review-core-interns
