/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_univ_mlv_unitex_UnitexLibAndJni */

#ifndef _Included_fr_univ_mlv_unitex_UnitexLibAndJni
#define _Included_fr_univ_mlv_unitex_UnitexLibAndJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    execUnitexTool
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_execUnitexTool___3Ljava_lang_String_2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    execUnitexTool
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_execUnitexTool__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    usingOffsetFile
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_usingOffsetFile
  (JNIEnv *, jclass);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    numberAbstractFileSpaceInstalled
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_numberAbstractFileSpaceInstalled
  (JNIEnv *, jclass);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    writeUnitexFile
 * Signature: (Ljava/lang/String;[C)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_writeUnitexFile__Ljava_lang_String_2_3C
  (JNIEnv *, jclass, jstring, jcharArray);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    writeUnitexFile
 * Signature: (Ljava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_writeUnitexFile__Ljava_lang_String_2_3B
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    writeUnitexFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_writeUnitexFile__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    writeUnitexFileUtf
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_writeUnitexFileUtf__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    writeUnitexFileUtf
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_writeUnitexFileUtf__Ljava_lang_String_2Ljava_lang_String_2Z
  (JNIEnv *, jclass, jstring, jstring, jboolean);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    getUnitexFileDataChar
 * Signature: (Ljava/lang/String;)[C
 */
JNIEXPORT jcharArray JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_getUnitexFileDataChar
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    getUnitexFileData
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_getUnitexFileData
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    getUnitexFileString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_getUnitexFileString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    removeUnitexFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_removeUnitexFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    createUnitexFolder
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_createUnitexFolder
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    removeUnitexFolder
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_removeUnitexFolder
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    renameUnitexFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_renameUnitexFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    copyUnitexFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_copyUnitexFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    setStdOutTrashMode
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_setStdOutTrashMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    setStdErrTrashMode
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_setStdErrTrashMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    installLogger
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_installLogger
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     fr_univ_mlv_unitex_UnitexLibAndJni
 * Method:    removeLogger
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univ_1mlv_unitex_UnitexLibAndJni_removeLogger
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
