/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_umlv_unitex_jni_UnitexJni */

#ifndef _Included_fr_umlv_unitex_jni_UnitexJni
#define _Included_fr_umlv_unitex_jni_UnitexJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    execUnitexTool
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fr_umlv_unitex_jni_UnitexJni_execUnitexTool___3Ljava_lang_String_2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    execUnitexTool
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fr_umlv_unitex_jni_UnitexJni_execUnitexTool__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    execRunLog
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fr_umlv_unitex_jni_UnitexJni_execRunLog___3Ljava_lang_String_2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    execRunLog
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fr_umlv_unitex_jni_UnitexJni_execRunLog__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    usingOffsetFile
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_usingOffsetFile
  (JNIEnv *, jclass);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    numberAbstractFileSpaceInstalled
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fr_umlv_unitex_jni_UnitexJni_numberAbstractFileSpaceInstalled
  (JNIEnv *, jclass);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    writeUnitexFile
 * Signature: (Ljava/lang/String;[C)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_writeUnitexFile__Ljava_lang_String_2_3C
  (JNIEnv *, jclass, jstring, jcharArray);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    writeUnitexFile
 * Signature: (Ljava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_writeUnitexFile__Ljava_lang_String_2_3B
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    writeUnitexFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_writeUnitexFile__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    writeUnitexFileUtf
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_writeUnitexFileUtf__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    writeUnitexFileUtf
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_writeUnitexFileUtf__Ljava_lang_String_2Ljava_lang_String_2Z
  (JNIEnv *, jclass, jstring, jstring, jboolean);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    appendUnitexFile
 * Signature: (Ljava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_appendUnitexFile
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    getUnitexFileDataChar
 * Signature: (Ljava/lang/String;)[C
 */
JNIEXPORT jcharArray JNICALL Java_fr_umlv_unitex_jni_UnitexJni_getUnitexFileDataChar
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    getUnitexFileData
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_fr_umlv_unitex_jni_UnitexJni_getUnitexFileData
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    getUnitexFileString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fr_umlv_unitex_jni_UnitexJni_getUnitexFileString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    removeUnitexFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_removeUnitexFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    createUnitexFolder
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_createUnitexFolder
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    removeUnitexFolder
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_removeUnitexFolder
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    renameUnitexFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_renameUnitexFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    copyUnitexFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_copyUnitexFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    unitexAbstractPathExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_unitexAbstractPathExists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    getFileList
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_fr_umlv_unitex_jni_UnitexJni_getFileList
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    setStdOutTrashMode
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_setStdOutTrashMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    setStdErrTrashMode
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_setStdErrTrashMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    installLogger
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_installLogger
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    removeLogger
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_fr_umlv_unitex_jni_UnitexJni_removeLogger
  (JNIEnv *, jclass);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    loadPersistentDictionary
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fr_umlv_unitex_jni_UnitexJni_loadPersistentDictionary
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    freePersistentDictionary
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fr_umlv_unitex_jni_UnitexJni_freePersistentDictionary
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    loadPersistentFst2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fr_umlv_unitex_jni_UnitexJni_loadPersistentFst2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    freePersistentFst2
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fr_umlv_unitex_jni_UnitexJni_freePersistentFst2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    loadPersistentAlphabet
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fr_umlv_unitex_jni_UnitexJni_loadPersistentAlphabet
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    freePersistentAlphabet
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fr_umlv_unitex_jni_UnitexJni_freePersistentAlphabet
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    getMajorVersionNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fr_umlv_unitex_jni_UnitexJni_getMajorVersionNumber
  (JNIEnv *, jclass);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    getMinorVersionNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fr_umlv_unitex_jni_UnitexJni_getMinorVersionNumber
  (JNIEnv *, jclass);

/*
 * Class:     fr_umlv_unitex_jni_UnitexJni
 * Method:    getSvnRevisionNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fr_umlv_unitex_jni_UnitexJni_getSvnRevisionNumber
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
