/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_univ_mlv_unitex_UnitexJNIExperiment */

#ifndef _Included_fr_univ_mlv_unitex_UnitexJNIExperiment
#define _Included_fr_univ_mlv_unitex_UnitexJNIExperiment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_univ_mlv_unitex_UnitexJNIExperiment
 * Method:    PerformUnitexToolByStringArray
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fr_univ_1mlv_unitex_UnitexJNIExperiment_PerformUnitexToolByStringArray
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
